name: Build and publish docker image

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      project_id:
        type: string
        required: true
      image_name:
        type: string
        required: true
      image_tag:
        type: string
      build_args:
        type: string
        default: development
    secrets:
      GCP_SERVICE_KEY:
        required: true
        
jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      # this step maybe is not needed
      - name: Configure gcloud access
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.GCP_SERVICE_KEY }}
          export_default_credentials: true
          
      - name: Set the tag
        run: |
          if [ -z "${{inputs.image_tag}}" ]
          then
            echo "final_tag=latest" >> $GITHUB_ENV
          else
            echo "final_tag=${{inputs.image_tag}}" >> $GITHUB_ENV
          fi
      
      - name: Get code
        uses: actions/checkout@v2
        
      - uses: RafikFarhad/push-to-gcr-github-action@v4
        with:
          gcloud_service_key: ${{ secrets.GCP_SERVICE_KEY }}
          registry: gcr.io
          project_id: ${{ inputs.project_id }}
          image_name: ${{ inputs.image_name }}
          image_tag: ${{ env.final_tag }}
          context: .
          build_args: BUILD_VERSION=${{ inputs.build_args }}
