name: Deploy to cloud run

on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        required: true
      project_id:
        type: string
        required: true
      service_name:
        type: string
        required: true
      image_name:
        type: string
        required: true
      image_tag:
        type: string
      service_region:
        type: string
        default: us-central1
      deploy_params:
        type: string
        default: --no-traffic
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      project_id:
        type: string
        required: true
      service_name:
        type: string
        required: true
      image_name:
        type: string
        required: true
      image_tag:
        type: string
      service_region:
        type: string
        default: us-central1
      deploy_params:
        type: string
    secrets:
      GCP_SERVICE_KEY:
        required: true
  # Map the workflow outputs to job outputs
    outputs:
      deployed_service_url:
        description: "The url of the service deployed"
        value: ${{ jobs.deploy-cloud-run-service.outputs.deployed_service_url }} 
  
jobs:
  deploy-cloud-run-service:
    runs-on: ubuntu-latest
    environment: ${{inputs.environment}}
    # Map the job outputs to step outputs
    outputs:
      deployed_service_url: ${{ steps.last.outputs.service-url }}
    steps:
      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{inputs.project_id}}
          service_account_key: ${{secrets.GCP_SERVICE_KEY}}

      - name: Set the tag
        run: |
          if [ -z "${{inputs.image_tag}}" ]
          then
            echo "final_tag=${{github.sha}}" >> $GITHUB_ENV
          else
            echo "final_tag=${{inputs.image_tag}}" >> $GITHUB_ENV
          fi

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy ${{inputs.service_name}} \
            --region ${{inputs.service_region}} \
            --image gcr.io/${{inputs.project_id}}/${{inputs.image_name}}:${{env.final_tag}} \
            --quiet \
            ${{inputs.deploy_params}}

      - id: last
        run: echo "::set-output name=servicec-url::hello"
